# Configuração básica para JSF com JoinFaces
# Define o sufixo padrão das páginas JSF
# jsf.facelets.suffix=.xhtml
# Ativa o modo de desenvolvimento do JSF
# jsf.PROJECT_STAGE=Development
# Configura o prefixo dos arquivos de template
spring.mvc.view.prefix=/WEB-INF/templates/
spring.mvc.view.suffix=.xhtml
# Configura o servlet do JSF
# joinfaces.jsf.servlet.init-parameters.primefaces.THEME=saga
#spring.datasource.username=${DATABASE_USERNAME}
#spring.datasource.password=${DATABASE_PASSWORD}
#spring.datasource.url=${DATABASE_URL}


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.connection.autocommit=false

#spring.jpa.generate-ddl=true

#spring.security.user.name=admin
#spring.security.user.password=admin

# Configuração para mapeamento de recursos estáticos
# jsf.resource.external=true
# jsf.resource.directory=/static/

# Configurações do JoinFaces e JSF
jsf.project-stage=Development
jsf.primefaces.theme=bootstrap
jsf.primefaces.enable-lazy-loading=true
jsf.primefaces.client-side-validation=true
jsf.primefaces.font-awesome=true

# Configuração do servlet do JSF
server.servlet.context-path=/
server.servlet.session.timeout=30m

# Configuração de recursos estáticos
jsf.resource.external=true
jsf.resource.directory=/static/

# Alterar a porta do servidor
server.port=8080

